// Shared exercise data for the Playground fitness section.
// cat: push | pull | legs | core | mobility
// level: 1 beginner · 2 intermediate · 3 advanced
window.EXERCISES = [
{id:"goblet-squat",name:"Goblet Squat",cat:"legs",muscles:"Quads · Glutes · Core",level:1,
 cues:["Hold a dumbbell at your chest, elbows tucked","Feet shoulder-width, toes slightly out","Sit back and down, knees track over toes","Keep chest up, drive through heels to stand"],
 mistakes:["Knees caving inward","Heels lifting off the floor","Rounding the lower back at the bottom"]},
{id:"bw-squat",name:"Bodyweight Squat",cat:"legs",muscles:"Quads · Glutes",level:1,
 cues:["Feet shoulder-width apart, arms forward for balance","Push hips back like sitting in a chair","Lower until thighs are parallel","Stand tall, squeeze glutes at the top"],
 mistakes:["Knees collapsing inward","Chest dropping forward","Not going deep enough"]},
{id:"rdl",name:"Romanian Deadlift",cat:"legs",muscles:"Hamstrings · Glutes · Back",level:2,
 cues:["Soft knees, dumbbells in front of thighs","Hinge at the hips, push glutes back","Lower until you feel a hamstring stretch","Squeeze glutes to return, don't hyperextend"],
 mistakes:["Rounding the back","Bending the knees too much (turns into a squat)","Letting weights drift away from legs"]},
{id:"lunge",name:"Walking Lunge",cat:"legs",muscles:"Quads · Glutes · Hamstrings",level:1,
 cues:["Step forward, lower until both knees hit 90°","Front knee over ankle, not past toes","Torso tall, core braced","Push through the front heel to step through"],
 mistakes:["Front knee shooting past toes","Leaning the torso forward","Short choppy steps"]},
{id:"glute-bridge",name:"Glute Bridge",cat:"legs",muscles:"Glutes · Hamstrings",level:1,
 cues:["Lie on back, knees bent, feet flat","Drive through heels, lift hips","Squeeze glutes hard at the top for 2 seconds","Lower slowly, don't arch the lower back"],
 mistakes:["Arching the back instead of squeezing glutes","Feet too far from body","Rushing the reps"]},
{id:"step-up",name:"Dumbbell Step-Up",cat:"legs",muscles:"Quads · Glutes",level:2,
 cues:["Hold dumbbells at sides, face a bench or box","Step up with full foot, drive through heel","Stand tall on the box, don't push off the back leg","Lower with control, alternate legs"],
 mistakes:["Pushing off the trailing leg","Knee caving in on the step","Using momentum"]},
{id:"calf-raise",name:"Standing Calf Raise",cat:"legs",muscles:"Calves",level:1,
 cues:["Stand tall, hold a dumbbell in one hand","Rise onto the balls of your feet","Pause 1 second at the top","Lower slowly below the starting point"],
 mistakes:["Bouncing at the bottom","Rolling ankles outward","Bending the knees"]},
{id:"pushup",name:"Push-Up",cat:"push",muscles:"Chest · Shoulders · Triceps · Core",level:1,
 cues:["Hands under shoulders, body in a straight line","Lower chest to the floor with control","Elbows at ~45° from the body","Push the floor away, don't shrug"],
 mistakes:["Hips sagging","Flaring elbows to 90°","Half reps"]},
{id:"incline-pushup",name:"Incline Push-Up",cat:"push",muscles:"Chest · Shoulders · Triceps",level:1,
 cues:["Hands on a bench or sturdy table","Body straight from head to heels","Lower chest to the bench edge","Great starter before floor push-ups"],
 mistakes:["Piking hips up","Letting the head droop","Going too fast"]},
{id:"db-bench",name:"Dumbbell Bench Press",cat:"push",muscles:"Chest · Shoulders · Triceps",level:2,
 cues:["Lie back, dumbbells at chest level","Press up, dumbbells meet over chest","Lower slowly for 2 seconds, elbows ~45°","Keep feet flat, slight arch in back"],
 mistakes:["Bouncing dumbbells off the chest","Flaring elbows wide","Lifting hips off the bench"]},
{id:"ohp",name:"Dumbbell Overhead Press",cat:"push",muscles:"Shoulders · Triceps",level:2,
 cues:["Dumbbells at shoulder height, palms forward","Brace core, squeeze glutes","Press straight up, biceps by ears","Lower with control to shoulders"],
 mistakes:["Arching the lower back","Shrugging shoulders to ears","Pressing forward instead of up"]},
{id:"dips",name:"Bench Dips",cat:"push",muscles:"Triceps · Chest · Shoulders",level:2,
 cues:["Hands on bench edge behind you, legs extended","Lower until elbows hit 90°","Keep shoulders down, away from ears","Press back up without locking hard"],
 mistakes:["Shrugging shoulders","Going too deep (shoulder strain)","Letting elbows flare wide"]},
{id:"db-row",name:"One-Arm Dumbbell Row",cat:"pull",muscles:"Lats · Upper Back · Biceps",level:1,
 cues:["One knee and hand on bench, back flat","Pull dumbbell to hip, elbow to ceiling","Squeeze shoulder blade at the top","Lower slowly, feel the stretch"],
 mistakes:["Rotating the torso","Rounding the back","Shrugging the weight up"]},
{id:"lat-pulldown",name:"Lat Pulldown",cat:"pull",muscles:"Lats · Biceps",level:1,
 cues:["Grip slightly wider than shoulders","Pull the bar to your upper chest","Lean back just slightly, chest up","Control the return, don't let it yank you"],
 mistakes:["Pulling behind the neck","Swinging the torso","Half range of motion"]},
{id:"pullup",name:"Pull-Up / Chin-Up",cat:"pull",muscles:"Lats · Biceps · Upper Back",level:3,
 cues:["Hang with a full grip, engage shoulders down","Pull chest to the bar","Lower all the way with control","Use a band for assistance if needed"],
 mistakes:["Kipping/swinging","Not going through full range","Craning the neck over the bar"]},
{id:"face-pull",name:"Face Pull",cat:"pull",muscles:"Rear Delts · Upper Back",level:2,
 cues:["Rope at eye level, thumbs toward you","Pull to your forehead, elbows high","Rotate so knuckles face the ceiling","Squeeze shoulder blades together"],
 mistakes:["Pulling to the chin instead of forehead","Dropping elbows","Using too much weight"]},
{id:"inverted-row",name:"Inverted Row",cat:"pull",muscles:"Lats · Upper Back · Biceps",level:2,
 cues:["Bar at waist height, hang underneath","Body straight like a plank","Pull chest to the bar","Harder: straighten legs; easier: bend knees"],
 mistakes:["Hips sagging","Shortening the range","Flaring elbows"]},
{id:"plank",name:"Forearm Plank",cat:"core",muscles:"Abs · Obliques · Glutes",level:1,
 cues:["Elbows under shoulders, body straight","Squeeze glutes and brace abs","Breathe steadily, don't hold breath","Start with 3×30s, build up"],
 mistakes:["Hips sagging or piking","Holding your breath","Letting the head hang"]},
{id:"dead-bug",name:"Dead Bug",cat:"core",muscles:"Deep Core · Abs",level:1,
 cues:["Lie on back, arms up, knees at 90°","Press lower back into the floor","Extend opposite arm and leg slowly","Return and switch sides, no arching"],
 mistakes:["Lower back arching off the floor","Moving too fast","Holding breath"]},
{id:"bird-dog",name:"Bird Dog",cat:"core",muscles:"Core · Glutes · Back",level:1,
 cues:["On all fours, hands under shoulders","Extend opposite arm and leg","Keep hips level, don't rotate","Hold 2 seconds, switch sides"],
 mistakes:["Rotating the hips open","Arching the lower back","Rushing through reps"]},
{id:"pallof",name:"Pallof Press",cat:"core",muscles:"Obliques · Deep Core",level:2,
 cues:["Band at chest height, stand sideways","Hold handle at chest, step out for tension","Press straight out, resist the pull","Bring back in slowly, don't rotate"],
 mistakes:["Letting the band rotate you","Leaning away from the anchor","Rushing the press"]},
{id:"band-pullapart",name:"Band Pull-Apart",cat:"mobility",muscles:"Rear Delts · Upper Back",level:1,
 cues:["Hold a light band at shoulder width","Pull apart until it touches your chest","Squeeze shoulder blades together","Control the return, 15-20 reps"],
 mistakes:["Shrugging shoulders up","Bending the elbows too much","Using a band that's too heavy"]},
{id:"hip-flexor",name:"Half-Kneeling Hip Flexor Stretch",cat:"mobility",muscles:"Hip Flexors · Quads",level:1,
 cues:["Kneel on one knee, other foot forward","Tuck pelvis under slightly","Shift forward until you feel the stretch","Hold 30s each side, breathe deeply"],
 mistakes:["Arching the lower back","Leaning the torso forward","Bouncing"]},
{id:"wall-slide",name:"Wall Slide",cat:"mobility",muscles:"Shoulders · Upper Back",level:1,
 cues:["Back flat against a wall, arms in goalpost","Slide arms up without losing contact","Keep ribs down, don't arch","Great desk-worker reset"],
 mistakes:["Arms leaving the wall","Ribs flaring out","Shrugging"]},
{id:"thoracic",name:"Thoracic Opener",cat:"mobility",muscles:"Mid Back · Chest",level:1,
 cues:["Lie on your side, knees bent, arms forward","Open the top arm like a book","Follow your hand with your eyes","Hold 5 breaths, switch sides"],
 mistakes:["Letting the knees lift","Forcing the range","Holding your breath"]}
];
window.CATS = {push:"💪 Push",pull:"🪢 Pull",legs:"🦵 Legs",core:"🧱 Core",mobility:"🤸 Mobility"};
window.LEVELS = {1:"Beginner",2:"Intermediate",3:"Advanced"};
